services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fastapp:${FASTAPP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      FASTAPP_HOST: 0.0.0.0
      FASTAPP_DB_FILE: /db_data/db.sqlite3
    volumes:
      - fastapp-db-data:/db_data/



volumes:
  fastapp-db-data:
    name: fastapp-db-data
